baseURL = 'https://changchen.me'
languageCode = 'zh-hans'
title = "Henry Z's blog"
theme = 'nostyleplease'

ignoreLogs = ['warning-goldmark-raw-html']

[permalinks]
  [permalinks.page]
    posts = '/blog/:year:month:day/:slugorcontentbasename/'
  [permalinks.section]
    posts = '/archives/'

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe= true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.extras]
      [markup.goldmark.extensions.extras.mark]
        enable = true

[params]
  description = "Henry Z's blog"
  images = ['site-feature-image.jpg']

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
